"""pass name change

Revision ID: 058b013b3cec
Revises: 8840df5e65e1
Create Date: 2023-11-07 10:11:16.058148

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '058b013b3cec'
down_revision = '8840df5e65e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('_password_hash', sa.String(), nullable=True))
        batch_op.drop_column('_pass_hash')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('_pass_hash', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('_password_hash')

    # ### end Alembic commands ###
