"""initial migration

Revision ID: 8840df5e65e1
Revises: 
Create Date: 2023-11-06 14:05:16.318318

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8840df5e65e1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cocktails',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('base', sa.String(), nullable=False),
    sa.Column('instruction', sa.String(), nullable=False),
    sa.Column('image', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cocktails'))
    )
    op.create_table('meals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('origin', sa.String(), nullable=False),
    sa.Column('base', sa.String(), nullable=False),
    sa.Column('instruction', sa.String(), nullable=False),
    sa.Column('image', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_meals'))
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('_pass_hash', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_table('cocktailreviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('cocktail_id', sa.Integer(), nullable=True),
    sa.Column('comment', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['cocktail_id'], ['cocktails.id'], name=op.f('fk_cocktailreviews_cocktail_id_cocktails')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_cocktailreviews_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cocktailreviews'))
    )
    op.create_table('favoritecocktails',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('cocktail_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cocktail_id'], ['cocktails.id'], name=op.f('fk_favoritecocktails_cocktail_id_cocktails')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_favoritecocktails_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_favoritecocktails'))
    )
    op.create_table('favoritemeals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('meal_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['meal_id'], ['meals.id'], name=op.f('fk_favoritemeals_meal_id_meals')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_favoritemeals_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_favoritemeals'))
    )
    op.create_table('mealreviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('meal_id', sa.Integer(), nullable=True),
    sa.Column('comment', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['meal_id'], ['meals.id'], name=op.f('fk_mealreviews_meal_id_meals')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_mealreviews_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mealreviews'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mealreviews')
    op.drop_table('favoritemeals')
    op.drop_table('favoritecocktails')
    op.drop_table('cocktailreviews')
    op.drop_table('users')
    op.drop_table('meals')
    op.drop_table('cocktails')
    # ### end Alembic commands ###
